### PR TITLE
Added node prepare script for windows support

### PR DESCRIPTION
**Pull request by bert-w**
#6 

I originally created a `package.json` in the root directory that was named `titanium-angular`, but then I noticed this is actually a collection of packages, since that name is already used in `packages/titanium-angular/package.json`.

So instead of a `npm run prepare` command, you have to run `node ./prepare.js` from the root of the project to install the node modules. The root `package.json` only contains a "dependencies" key.

**Note that this currently still fails on Windows**, because of the error `npm ERR! titanium-angular@0.1.0 clean: 'rm -rf ./dist'` (which are linux commands in another file  `packages/titanium-angular/package.json`).

### CODE REVIEW

**Comment by ewanharris** [comment]
@bert-w Did you catch my reply to your comment on that commit?

**Comment by bert-w** [comment]
Sorry i forgot to reply. I didnt know this was possible. Apparently if i want to execute it from the terminal id have to use "npx" like `npx rimraf ./mydir`, but the "scripts" from `package.json` go somewhere different, and it works just like that.

Anyway, seems like that commit will fix the issue mentioned.


Van: Ewan Harris
Verstuurd: maandag 14 mei 15:12
Onderwerp: Re: [appcelerator/titanium-angular] Added node prepare script for windows support (#7)
Aan: appcelerator/titanium-angular
Cc: Bert, Mention


@bert-w<https://github.com/bert-w> Did you catch my reply to your comment on that commit?

**Comment by hansemannn** [comment]
@bert-w Can you either cherry-pick the changes from @ewanharris or can @ewanharris push it directly?

**Comment by bert-w** [comment]
I believe they can be combined just like that, although i dont know what other changes ewan had in mind.

**Comment by janvennemann** [comment]
Closing due to a major project restructure. We now only have one package as all other moved to https://github.com/appcelerator/titanium-webpack-devkit. While doing that, I incorporated the changes from @ewanharris to use platform independent tools in the npm scripts.

You can now use `npm run bootstrap` to install dependencies for both titanium-angular and the example app.

**Pull request closed without merging**
